### ISSUE TITLE
lsvo_model_responces bad inserts

### ISSUE THREAD

**Issue by espinm2** [graphics-rpi/oasis#25]
As of right now the ID field contains model_<num> rather than just the number required. Please fix!

**Comment by JerameyATyler** [comment]
Wrote sql script to replace 'model_' with '' in all ids. 

`delete from lsvo_model_responces where id is NULL;

DO $$
DECLARE
    rec CURSOR FOR SELECT id FROM lsvo_model_responces;
    new_id TEXT;

BEGIN
    FOR ro IN rec LOOP
        new_id := replace(ro.id, 'model_', '');

```
    EXECUTE 'UPDATE lsvo_model_responces SET id = ''' || new_id || ''' WHERE id = '''|| ro.id || '''';
END LOOP;
```

END$$;

select \* from lsvo_model_responces;`
